### ISSUE TITLE
Issue with setting up HTTPS connection

### ISSUE THREAD

**Issue by StEtz** [fescobar/allure-docker-service-ui#35]
Hi,

I have setup your Docker-Server + Docker-UI services and wanted to add an HTTPs server in front of it.

So basically:
`[AllureSrv] <-- http --> [AllureUI] <-- http --> [httpProxy] <--- https (Internet)`

Therefore I understood that in the docker-compose file I have to enable the “TLS” environment variable + add some credentials.
However when I open the Website using the https URL I am getting an error ![Screenshot](https://github.com/fescobar/allure-docker-service-ui/assets/29714373/50453527-4b6a-4e78-b4fd-814e07642c94)

When I configure my httpProxy to contact the AllureServer directly (e.g. to see the swagger page via https) it works. So the configuration of my httpProxy is correct. 

It seems a problem in the AllureUI Implementation.

Also: I connected into the docker container of the AllureUI serice and could reach the AllureSrv container, via: 
`curl https://allure_srv:5050/`
So they do have a connection.

Do you have an idea what I am doing wrong here?

This is my docker-compose file:

```
version: "3.8"
services:
  allure_srv:
    image:
      frankescobar/allure-docker-service:2.21.0
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=NONE
      - KEEP_HISTORY=1
      - SECURITY_USER=…
      - SECURITY_PASS=…
      - SECURITY_ENABLED=1
      - TLS=1
      - DEV_MODE=0
    volumes:
      - /allure_data/projects:/app/projects
    hostname:
      allure_srv
    ports:
      - 5050:5050
    networks:
      my_network:  

  allure_ui:
    image:
      frankescobar/allure-docker-service-ui:7.0.3
    environment:
      - ALLURE_DOCKER_API_URL=http://…:5050
    ports:
      - 5252:5252
    depends_on:
      - allure_srv
    hostname:
      allure_ui
    networks:
      my_network:

  http_proxy:
    image:
      caddy:alpine
    depends_on:
      - allure_srv
    hostname:
      caddy
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/allure/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=…
      - EMAIL=…
      - LOG_FILE=/data/access.log
    networks:
      my_network: 

volumes:
  caddy_data:
  caddy_config:

networks:
  my_network:

```
