### ISSUE TITLE
PREFIX does not change path for static files

### ISSUE THREAD

**Issue by rayjlinden** [fescobar/allure-docker-service-ui#7]
I'm trying to put the ui behind a proxy.

I set URL_PREFIX: "/allureui"

However, the page once it loads is trying to get assets like:
/static/js/2.305ecc37.chunk.js

Is there something I can do to serve the assets out the url_prefix as well?

**Comment by fescobar** [comment]
@rayjlinden what proxy are you using? and what is your configuration? are you using Kubernetes?

**Comment by rayjlinden** [comment]
I'm using caddy2. (caddyserver.com)

I wanted to serve the UI out of a sub dir.  I set the env var: URL_PREFIX:
"/allureui"

My Caddyfile config looks like this:
```
        route /env-config.js {
                reverse_proxy http://allureui:5252
        }
        route /static/* {
                reverse_proxy http://allureui:5252
        }
        route /allureui/* {
                jwt

                reverse_proxy http://allureui:5252
        }
```

I had to add the routes for /static/* and /env-config.js -- then everything
worked.  However, I would have expected
the references to the static assets and env-config.js to also be prefixed
with /allureui/

**Comment by fescobar** [comment]
@rayjlinden you have to set up a little different when it's a Single Page Aplication (SPA). Fortunately, it's work for you.
I will see how can I improve that part because as you said I'm not totally convinced how it's working now.

**Comment by oleksandr-hyuna** [comment]
Same with Nginx:
docker-compose
```
version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
      URL_PREFIX: "/allure"
    ports:
      - "5050:5050"
    volumes:
      - /etc/allure/allure-results:/app/allure-results
      - /etc/allure/allure-reports:/app/default-reports
  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://nginx.domain.com"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: "/allure"
      URL_PREFIX: "/allureui"
    ports:
      - "5252:5252"

```
Works only with separate env-config.js and static route:

```
    location /allure/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://allure:5050;
    }
    location /allureui/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://allure:5252;
    }
    location /env-config.js {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://allure:5252;
    }
    location /static/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://allure:5252;
    }
```

That's can conflict with my "location /" that is not ok as for me

**Comment by fescobar** [comment]
Thanks @oleksandr-hyuna for the info. I will use this when I try to fix this problem. It's in the backlog.

**Comment by sharmau5** [comment]
Facing the same issue. I am using Istio virtual services and have to map the root `/` location to the ui to get the static assets to load. A fix will be great as this is not going to work long-term.

```   
    - match:
        - uri:
            prefix: /ids-reports-api
      rewrite:
        uri: /
      route:
        - destination:
            host: ids-reports
            port:
              number: 5050
    - match:
        - uri:
            prefix: /ids-reports-ui
      route:
        - destination:
            host: ids-reports
            port:
              number: 5252
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: ids-reports
            port:
              number: 5252
```
